* Málræn martröð á miðvikudögum
Jæja þá píps, eruð þið reddí?
Ég von'etta soundi, passlega sneddí.
Íslenskan okkar, er beautiful björt.
En behold the ísl-enska! None skal be hurt.

Tyllið yourselves og takið sem true,
ég er smá twisted, en ekk'út úr kú.
Your merry málgjörð, is in for a hnekki.
Komandi málkennd? Hopefully ekki.

Lendið mér eyru, eitt öggu suggestion,
á miðvikudögum, æfum expression!
Ekkert úr English, íslenskan dátt,
einungis þá, for slettulaust clout.

Á hverju corner, adventure bíður,
kannski smá Ísl, svo English er líður.
The gola is hér, gólar nú plenty.
What ghastly súpu, höfum við lent í?

Á tímum tölvunar, tangled og twined,
Verðum við weavers, vörðum inclined.
Semjum vor söng, words munu fljúga,
samþættar tongues, söngvar er snúa.

Fléttum mál saman, fluent og vel,
hear as it flæðir, straight uppúr hel.
Miss me með þau, þessi málaskil,
verðum mentally frjáls, en bara um bil.

Ruckus og rugl, í Reykjavík city,
runaway vextir, ekki svo pretty.
Bólgandi loans og booming hús,
soldið bewildering, of mikið booze?

Seint um evening, þegar sól goes down,
syrgir each, their húsnæðislán.
Við horfum svo yfir, the bláa bay,
fjarri banks, við munum stay.

Undir the starlight, undir the dark,
ísl-enskan veitir creative spark.
Hræðist not, what framtíðin holds,
hunsið né ei, þá ísl-ensk' unfolds.

Stærðarinnar steik af language stúf,
ein steaming blanda af old og new.
Þrátt fyrir thrills er ísl-enskan gefur,
þá fengi ég chills, ef hlustað þú hefur.
